- name: Deploy Docker image to K8
  hosts: localhost
  user: ubuntu


  tasks:
     - name: Clear previous deployment
      shell: 
        cmd: kubectl delete deployment devopscw2 

    - name: Create deployment to Kubernetes
      shell: 
        cmd: kubectl create deployment devopscw2 --image=danielmckain/dm_devops_cw2_r:latest